server.port=8081
spring.application.name=user-service

# Configuração do Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/ms_user?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=M3l1ss40251&
spring.jpa.hibernate.ddl-auto=update

# CloudAMQP
spring.rabbitmq.host=beaver.rmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=rmllbeok
spring.rabbitmq.password=rKOrVZ-GNJ5dbqSblwkKFWxmN2weyOLo
spring.rabbitmq.virtual-host=rmllbeok

spring.rabbitmq.ssl.enabled=true

spring.rabbitmq.connection-timeout=5000
broker.queue.email.name=default.email